### ISSUE TITLE
making this work with ejabberd 15.xx

### ISSUE THREAD

**Issue by biskit** [dirkmoors/pyejabberd#25]
great work in exposing via python and xmlrpc!

a few comments to make sample working:
1. firstly the port it connects to should be 4560 (default for ejabberd_xmlrpc)

``` python
# Create a client and authenticate with elevated user 'bob@example.com'
client = EjabberdAPIClient(host='localhost', port=4560, username='bob', password='p@$$wd', user_domain='example.com',   protocol='https')
```

and this section of ejabberd.yml should be uncommented

``` yml
listen:
  -
    port: 4560
    module: ejabberd_xmlrpc
    maxsessions: 10
    timeout: 5000
    access_commands:
      xmlrpc:
        commands: all
      ## Local
      xmlrpc_access:
        commands: all
    options: []
```

and this added if you want admin commands to work

``` yml
acl:
  xmlrpc_users:
    user:
      - "<adminuser>": "<domain>"

access:
  xmlrpc_access:
    xmlrpc_users: allow
```

like this one:

``` python
# Get a list of users that are on the server
registered_users = client.registered_users('example.com')
# result is in the format [{'username': 'bob', ...}]
# Register a new user
client.register(user='alice', host='example.com', password='@l1cepwd')
```
